# Generated by Django 5.1.3 on 2024-11-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
