# Generated by Django 5.1.3 on 2024-11-18 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender_alter_user_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Alamat Pengiriman')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Nomor Telepon')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto Profil')),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10, verbose_name='Jenis Kelamin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
